services:
  - type: web
    name: ai-video-agent
    env: python
    buildCommand: "pip install --no-cache-dir -r Requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: WHISPER_MODEL
        value: base
      - key: YTDLP_COOKIE_FILE
        value: cookies.txt
        sync: false
